apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgres
          image: postgres:13.16
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: ecommerce
          - name: POSTGRES_PASSWORD
            value: Pg1234
          - name: POSTGRES_DB
            value: ecommerce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeshop
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fakeshop
  template:
    metadata:
      labels:
        app: fakeshop
    spec:
      containers:
        - name: fakeshop
          image: vercoza/fake-shop:v1.0
          ports:
          - containerPort: 5000
          env:
          - name: DB_HOST
            value: postgre
          - name: DB_USER
            value: ecommerce
          - name: DB_PASSWORD
            value: Pg1234
          - name: DB_NAME
            value: ecommerce
          - name: FLASK_APP
            value: index.py
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  type: ClusterIP
  selector:
    app: postgre
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: fakeshop
spec:
  type: LoadBalancer
  selector:
    app: fakeshop
  ports:
  - port: 80
    targetPort: 5000