name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Teste"
  CD:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Teste"
  
